### ISSUE TITLE
Doom Emacs mixing fonts note issue

### ISSUE THREAD

**Issue by ulysses4ever** [dschapman/dschapman-com#85]
Hey! Your [note][note] is high on Google results for Doom Emacs variable pitch font. Congrats! There's one issue there though. Namely, it has the following snippet:

[note]: https://www.dschapman.com/notes/33f4867d-dbe9-4c4d-8b0a-d28ad6376128

```
(use-package mixed-pitch
  :hook
  ;; If you want it in all text modes:
  (text-mode . mixed-pitch-mode))
```

The proper mechanism in Doom Emacs is `use-package!` (note the bang), I believe.

**Comment by dschapman** [comment]
Thanks so much, I appreciate you pointing that out. I fixed my note and next time I build my website it should be reflected.

**Comment by ulysses4ever** [comment]
Cool, thank you!
